# Generated by Django 5.1.4 on 2026-06-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from the title; override for a custom URL.', max_length=200, unique=True)),
                ('body', models.TextField(blank=True, help_text='Page content. HTML is rendered as-is.')),
                ('published', models.BooleanField(default=False, help_text='Unpublished pages are hidden from the site and its navigation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
