# Generated by Django 5.1.4 on 2026-06-28 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pages/files/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='pages.page')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
