# Generated by Django 5.1.4 on 2026-06-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_pagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body',
            field=models.TextField(blank=True, help_text='Page content, edited with the rich-text editor.'),
        ),
    ]
