# Generated by Django 5.2.15 on 2026-07-11 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Admin-facing label to tell logos apart; not shown to visitors.', max_length=200)),
                ('image', models.ImageField(upload_to='logos/')),
                ('accent_color', models.CharField(help_text='Hex color paired with this logo, e.g. #aabbcc or #abc.', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a 3- or 6-digit hex color, e.g. #abc or #aabbcc.', regex='^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')])),
                ('is_active', models.BooleanField(default=True, help_text='Inactive logos are excluded from the random pool.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
