# Generated by Django 5.1.4 on 2026-06-27 21:46

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Illustration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from the title; override for a custom URL.', max_length=200, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Manual display order; lower numbers appear first.')),
                ('featured', models.BooleanField(default=False, help_text='Highlight one piece of this type on the homepage.')),
                ('published', models.BooleanField(default=False, help_text='Unpublished pieces are hidden from the public site.')),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional; auto-derived from the piece when left blank.', upload_to=portfolio.models.thumbnail_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='illustrations/')),
            ],
            options={
                'ordering': ['order', 'title'],
                'abstract': False,
            },
        ),
    ]
