# Generated by Django 5.1.4 on 2026-06-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_comic_comicpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='published',
            field=models.BooleanField(default=True, help_text='Unpublished pieces are hidden from the public site.'),
        ),
        migrations.AlterField(
            model_name='illustration',
            name='published',
            field=models.BooleanField(default=True, help_text='Unpublished pieces are hidden from the public site.'),
        ),
        migrations.AlterField(
            model_name='sketchbooksample',
            name='published',
            field=models.BooleanField(default=True, help_text='Unpublished pieces are hidden from the public site.'),
        ),
    ]
