# Generated by Django 5.1.4 on 2026-06-28 19:42

import django.db.models.deletion
import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_comic_published_alter_illustration_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from the title; override for a custom URL.', max_length=200, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Manual display order; lower numbers appear first.')),
                ('published', models.BooleanField(default=True, help_text='Unpublished pieces are hidden from the public site.')),
                ('featured', models.BooleanField(default=False, help_text='Highlight one piece of this type on the homepage.')),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional; auto-derived from the piece when left blank.', upload_to=portfolio.models.thumbnail_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(blank=True, help_text='Rich body. HTML is rendered as-is (WYSIWYG arrives later).')),
                ('category', models.ForeignKey(help_text='Grouping label for the storyboards section.', on_delete=django.db.models.deletion.PROTECT, related_name='storyboards', to='portfolio.category')),
            ],
            options={
                'ordering': ['order', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoryboardDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('embed_html', models.TextField(blank=True)),
                ('embed_width', models.PositiveIntegerField(blank=True, null=True)),
                ('embed_height', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the storyboard; lower numbers first.')),
                ('storyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='portfolio.storyboard')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoryboardPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='storyboards/pdfs/')),
                ('display_name', models.CharField(help_text='Label shown for the download link.', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the storyboard; lower numbers first.')),
                ('storyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='portfolio.storyboard')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StoryboardVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('embed_html', models.TextField(blank=True)),
                ('embed_width', models.PositiveIntegerField(blank=True, null=True)),
                ('embed_height', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the storyboard; lower numbers first.')),
                ('poster_url', models.URLField(blank=True, max_length=500)),
                ('storyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='portfolio.storyboard')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
