# Generated by Django 5.1.4 on 2026-06-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_storyboard_storyboarddeck_storyboardpdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyboard',
            name='body',
            field=models.TextField(blank=True, help_text='Rich body, edited with the rich-text editor (Slice 12).'),
        ),
    ]
