# Generated by Django 5.1.4 on 2026-06-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_storyboard_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyboardpdf',
            name='display_name',
            field=models.CharField(blank=True, help_text='Label shown for the download link. Defaults to the filename.', max_length=200),
        ),
    ]
